name: SpigotSamplePlugin
version: "1.0"
api-version: "1.15"
main: jp.yuyu.SpigotSamplePlugin.Main
author: Hiroya_W
commands:
  hello:
    usage: "/<command>"
    description: "挨拶する"
    aliases:
      - hi
  head:
    usage: "/<command> [Player]"
    description: "プレイヤーの頭を取得します"
    permission: minecraft.command.give
  dice:
    usage: "/<command> [Max] [Count]"
    description: "サイコロを振る"